// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import event "github.com/eclipse/che-go-jsonrpc/event"

import mock "github.com/stretchr/testify/mock"

// ExecEventBus is an autogenerated mock type for the ExecEventBus type
type ExecEventBus struct {
	mock.Mock
}

// PeriodicallyCleanUpBus provides a mock function with given fields:
func (_m *ExecEventBus) PeriodicallyCleanUpBus() {
	_m.Called()
}

// Pub provides a mock function with given fields: e
func (_m *ExecEventBus) Pub(e event.E) {
	_m.Called(e)
}

// SubAny provides a mock function with given fields: consumer, types
func (_m *ExecEventBus) SubAny(consumer event.Consumer, types ...string) {
	_va := make([]interface{}, len(types))
	for _i := range types {
		_va[_i] = types[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, consumer)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
